language: node_js
node_js:
- 6
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: rPdwhI5vc42jSaHiIe8/hzZ1Fp+uFlTAzFKDWs4K81f1RZ4j/heQgp8hkDZoUHJtdR/2z8/ZxAymqMWzo/JCO/1i6Vn1s6r9szAYMw2Np+13+oI8OQaYJH+2JhN5vF5BuKM2GhrzXyvZACdV4GH3BkfZTKPi3kBYIhvWguctT/ijhf3i8UZEDZf3kQHxQa1DOgBqzBLCDVEMCS0Er6oCm349mu/Oujs6pcsnbRjJQkvBhzzernXza+2FHdY52FB1b8AzmT8Yxac5sNj5RzZFxzBj+JiUhbBHYzEDhhOMsPkC6OI+Tf4SkGEj3oyZ+hrxonvAkTE5wivnTqhOahOZOMBnKgxIqqL3nGD9zyScZEFNfOrRE++yMuJ56r+6UpcW7V/lB1/6pqzDyxDFnD1T6y28rHPAEkFdaxwJcAQ10qYpTKGz0LyaJG6o6L3FgSG28tgra+9C89NMJA1Gsayqc93X1LhavEceIdvHbKQ3LNFRpguckmP8QYeM6/oSY8fm5czZNIL4dsET/0/rpF92cekaWwKqrX6F3OBXl0DA3V4+wpvhOwWDA5gHtKbO5jKdZ1I5uZRsa2vLxUf9JOt/nYofCjEkfcfu4lAfqOTJNIc1ZhOa3bPuyKactGIcj0itD7/NrpR+zB+WgKWi1ochRRntjlVySwlopiH+MQBFtys=
  app:
    dev: cdc-java-bootcamp
